#!/bin/bash

package=$1
prefix=$2
functype=$3
funcname=$4
outfile=$5

echo "// Auto generated by $0" >$outfile

echo "package" $(basename $package) >>$outfile

echo "import \"github.com/codomatech/goaccess.go/common\"" >>$outfile

for p in $package/*; do
    if [ ! -d $p ]; then continue; fi
    p=$(basename $p)
    echo "import $p \"$prefix/$p\"" >>$outfile
done

echo type Function $functype >>$outfile

echo "func Plugins() map[string]Function {" >>$outfile

echo "    plugins := make(map[string]Function)" >>$outfile

for p in $package/*; do
    if [ ! -d $p ]; then continue; fi
    p=$(basename $p)
    echo "    plugins[\"$p\"] = $p.$funcname" >>$outfile
done

echo -e "    return plugins\n}" >>$outfile
